language: go

go:
  - 1.10.5
  - 1.11.2

os: linux

dist: trusty

addons:
  sonarcloud:
    organization: "ilmaruk-github"

script:
  - go test -race -coverprofile=coverage.out ./...
  - sonar-scanner